### ISSUE TITLE
Support for exporting to raw bitmap, or adding text to the bottom or top of the QR Code

### ISSUE THREAD

**Issue by chetan-prime** [yeqown/go-qrcode#66]
Quite a few javascript libraries support adding a custom text like "Scan this code on your phone to open the app,,," etc.
It's easy to do this on javascript as fonts are inbuilt. But even on Go there are many libraries available that allow using system/custom fonts to do the same.

I request support for either:
1. Exporting the output image to raw Bitmap in-memory so my program can then blit the image onto another in-memory canvas which I can then add my custom text or other borders etc. into.
2. Add support within the program itself for "margin" so each QR code has "n" blank/white pixels all around, and within this margin the library supports printing text onto the image before exporting it using another font rendering library.

**Comment by yeqown** [comment]
The second has been supported by [standard writer](https://github.com/yeqown/go-qrcode/tree/main/writer/standard), and then, does request#1 mean you want an `image.Image` so that you can re-draw with QRCode?

Please provide some sample codes to help me understand your request. 
By the way, you can totally code your own [writer](https://github.com/yeqown/go-qrcode/tree/main/writer) to customize the QR Code image output.

**Comment by chetan-prime** [comment]
Thanks, I was able to use the WithCustomImageEncoder and my custom struct to capture the output image.Image when its passed for Encode().

This image.Image I am able to process with the gg graphics library to resize the QR & blit onto a larger gg canvas, into which I can then add custom text of my own. Basically the intent is show along with QR a message on screen for the user like "Please scan this image with your mobile device"

I am closing this issue as the library itself does its work of encoding a QR image very well. Only one minor issue is no ability to strictly control the output size, but I'm able to use the gg libraries scaling feature to resize the output QR image to a specific pixel width/height.

**Comment by yeqown** [comment]
> "Only one minor issue is no ability to strictly control the output size" 

@chetan-prime  Actually, you can, please refer to the method [Attribute](https://github.com/yeqown/go-qrcode/blob/5016f7765d9e35c57b31a28694f3e80e355c1968/writer/standard/writer.go#L84-L86) to understand the QR image size calculating formula, so that you can calculate out the border and block pixels with target QR image size you want.
