### ISSUE TITLE
How to get binary data of QRcode instead of writing to file？

### ISSUE THREAD

**Issue by jianmaikj** [yeqown/go-qrcode#67]

**Comment by yeqown** [comment]
https://pkg.go.dev/github.com/yeqown/go-qrcode/writer/standard#NewWithWriter

**Comment by siddarthkay** [comment]
@yeqown 

Thanks for building this library, it really helps me in implement the feature we want in our project.

As someone that is new to Go, 
I am unable to figure out how to get binary data or bytes from this library instead of getting the output in file format.

Could you please provide a very basic working example of how the `newWithWriter` func will work?

I visited https://pkg.go.dev/github.com/yeqown/go-qrcode/writer/standard#NewWithWriter but was unable to figure it out.

All I am looking for is some example similar to what is present here :https://github.com/yeqown/go-qrcode/blob/main/example/simple/main.go

Thanks again!

**Comment by yeqown** [comment]
@siddarthkay 

refresh `example/simple` you can get following codes, could this answer your question？

```go
	buf := bytes.NewBuffer(nil)
	wr := nopCloser{Writer: buf}
	w2 := standard.NewWithWriter(wr, standard.WithQRWidth(40))
	if err = qrc.Save(w2); err != nil {
		panic(err)
	}


	// copy base64 content to converter, then you can get the picture
	// https://codebeautify.org/base64-to-image-converter
	fmt.Printf("encoded base64 image:\n%s", base64.StdEncoding.EncodeToString(buf.Bytes()))
```

**Comment by siddarthkay** [comment]
Thanks @yeqown 
This does answer my question and would definitely help beginners and new consumers of your library!

After some research, experimentation and help from a friend, I got the desired output with the code below :

```
type WriterCloserByteBuffer struct {
    *bytes.Buffer
}

func (wc WriterCloserByteBuffer) Close() error {
    return nil
}

func NewWriterCloserByteBuffer() *WriterCloserByteBuffer {
    return &WriterCloserByteBuffer{bytes.NewBuffer([]byte{})}
}

func Test(t *testing.T) {
    buf := NewWriterCloserByteBuffer()

    qrc, err := qrcode.New("https://github.com/yeqown/go-qrcode")
    if err != nil {
        fmt.Printf("could not generate QRCode: %v", err)
        return
    }

    w := standard.NewWithWriter(buf)
    if err != nil {
        fmt.Printf("standard.New failed: %v", err)
        return
    }

    if err = qrc.Save(w); err != nil {
        fmt.Printf("could not save image: %v", err)
    }

    spew.Dump(buf.Bytes())
}
```
