### ISSUE TITLE
go pkg versioning for writer/standard

### ISSUE THREAD

**Issue by Shubhaankar-Sharma** [yeqown/go-qrcode#86]
Hi! Right now, to use the package we still have to use this import path `"github.com/yeqown/go-qrcode/writer/standard"`

but the qrcode package is on v2 `"github.com/yeqown/go-qrcode/v2"`

shouldn't the versioning for writer should also be something like this `"github.com/yeqown/go-qrcode/v2/writer/standard"`

it's because writer/standard has its own go.mod, is there a reason for it? ideally it should all be in a root go.mod file

**Comment by yeqown** [comment]
The writer has its own mod name, I didn't add v2 in its mod path since it looks weird to me while importing a writer which has a `v1.x` tag but it has a `v2` subpath.

And a writer can split packages for this repository, so its mod path should have no relation to this repository too.

This is not absolute, we can change this if it's necessary

**Comment by NickOttrando** [comment]
I'm also confused by this @yeqown, because following your docs, if i do this [exact example](https://github.com/yeqown/go-qrcode/blob/v2.2.2/example/with-logosize-multiplier/main.go), then I get the error 

> WithLogoSizeMultiplier not declared by package standard

Because it's pointing standard package to v1.2.1 which does not have this `WithLogoSizeMultiplier` function.

**Comment by yeqown** [comment]
> I'm also confused by this @yeqown, because following your docs, if i do this [exact example](https://github.com/yeqown/go-qrcode/blob/v2.2.2/example/with-logosize-multiplier/main.go), then I get the error
> 
> > WithLogoSizeMultiplier not declared by package standard
> 
> Because it's pointing standard package to v1.2.1 which does not have this `WithLogoSizeMultiplier` function.

@NickOttrando 
That's a mistake since the option API `WithLogoSizeMultiplier` doesn't contain by v1.2.1, you can try v1.2.2
