### ISSUE TITLE
Is WithLogoSizeMultiplier working?

### ISSUE THREAD

**Issue by robertocommit** [yeqown/go-qrcode#87]
I am running the example [with-logosize-multiplier](https://github.com/yeqown/go-qrcode/tree/main/example/with-logosize-multiplier) but unfortunately the function responsible to multiply the size of the logo in trwoing an error.

Thanks!

**Comment by yeqown** [comment]
Could you provide more error tips? Or describe what you expect and what you got actually? 

By the way, the option `WithLogoSizeMultiplier` doesn't mean **Multipy** the logo size, but validating the logo size can be applied to the QR code.

**Comment by robertocommit** [comment]
Ehy there, thanks for your reply. Indeed, I thought `WithLogoSizeMultiplier` multiplies the logo size.

Do you think a similar feature would be possibile?

**Comment by yeqown** [comment]
The option API leads a wrong semantics ~ Although it has added a comment. I'll change that in the future.

As for your question, personally, I would not implement it as a functionality of the standard writer, since there is an option [`WithLogoImage`](https://github.com/yeqown/go-qrcode/tree/main/writer/standard) for users to scale their logo image manually. Another reason is that scale means expanding and shrinking the image, it looks heavy for the standard writer.

Any PR is welcome!

**Comment by robertocommit** [comment]
Thanks a lot for your comments. Closing the issue, in case I will decide to work on it, will open a new one or re-open this one.
